export const DRAW_LETTERS = 'DRAW_LETTERS';
export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RUN_TIMER = 'RUN_TIMER';
export const UPDATE_SESSION_LENGTH = 'UPDATE_SESSION_LENGTH';
export const TOGGLE_ALARM_SOUND = 'TOGGLE_ALARM_SOUND';
export const RULES_MODAL_SWITCH = 'RULES_MODAL_SWITCH';
